// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXBawO-kz7oeZsYJWyGZpDgstKmcIuQoU',
    appId: '1:551268124948:web:03ba8046335744e28c5a01',
    messagingSenderId: '551268124948',
    projectId: 'fir-login-76dcc',
    authDomain: 'fir-login-76dcc.firebaseapp.com',
    storageBucket: 'fir-login-76dcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTzNgHiELWRqsOCLPw7wg_4Snoix39fbk',
    appId: '1:551268124948:android:0339231e810bb6d48c5a01',
    messagingSenderId: '551268124948',
    projectId: 'fir-login-76dcc',
    storageBucket: 'fir-login-76dcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRQysmoU6uFqCy_vw2WQ4tW5pDPBueJAc',
    appId: '1:551268124948:ios:b5bf5aefd97ad77f8c5a01',
    messagingSenderId: '551268124948',
    projectId: 'fir-login-76dcc',
    storageBucket: 'fir-login-76dcc.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRQysmoU6uFqCy_vw2WQ4tW5pDPBueJAc',
    appId: '1:551268124948:ios:b5bf5aefd97ad77f8c5a01',
    messagingSenderId: '551268124948',
    projectId: 'fir-login-76dcc',
    storageBucket: 'fir-login-76dcc.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXBawO-kz7oeZsYJWyGZpDgstKmcIuQoU',
    appId: '1:551268124948:web:17a10fc0fd61eb658c5a01',
    messagingSenderId: '551268124948',
    projectId: 'fir-login-76dcc',
    authDomain: 'fir-login-76dcc.firebaseapp.com',
    storageBucket: 'fir-login-76dcc.firebasestorage.app',
  );
}
